name: Turquoise Space - Apache JMeter - Docker Image CI / CD

on:
  push:
    branches: [ "ubuntu-23.10_openjdk-8u372b07_maven-3.9.3_jmeter-5.6.2" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      -
        name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S-%Z')"
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: true
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            turquoisespace/apache-jmeter:ubuntu-23.10_openjdk-8u372b07_maven-3.9.3_jmeter-5.6.2
            turquoisespace/apache-jmeter:${{ steps.date.outputs.date }}_${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
